### PR TITLE
Added Responsiveness to PayDues Page

### LINKED ISSUE #76: Mobile Responsiveness: PaydueFees
### Description

- PayDueFees Module is successfully created
- But there is a bug in that module
- The module is not responsive
- This must be fixed

### Screenshots

- Pay Due Fees Module
Screenshot 2022-10-04 234204

- Mobile View
mobile (1)

- Laptop view
Screenshot 2022-10-04 222914

- Code
code

### Additional information

- Maintain Folder Structure
- Use MUI Components only
- Refrain from creating `.css` files, stick to styled components only.

### PR DESCRIPTION
**Pull request by Alcadeus0**
# Issue  📐

- **I Alcadeus0 have worked for #76**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #76**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**
image

The bug seemed to be from having the styles be applied to the table alongwidth the left align.
---

### CODE REVIEW

**Comment by warmachine028** [comment]
This is still unresponsive. Please fix this

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Please fix the issue

**Comment by Alcadeus0** [comment]
Hmm weird, I'll look into it

**Comment by warmachine028** [comment]
> Hmm weird, I'll look into it

**Clue:** Try removing padding, adjusting margin in small devices, also adjust fontSizes, might fix it

**Comment by Alcadeus0** [comment]
Made some new changes. Let me know if everything goes well

**Review by warmachine028 — APPROVED** [review]
LOoks Good to me. Don't forget to star the repo 💚

**Pull request merged**
