### PR TITLE
Add date picker for organisational calendar component

### LINKED ISSUE #32: Organizational Calendar 📆🗓️
### Description

- Organizational Calendar must be designed for UEMCRP
- Currently the original Page of [iemcrp] logs the user out to redirect to the organizational calendar.
- This action is really cumbersome for the users.
- The component must be designed using MUI and Styled Components only. 

[iemcrp]: https://www.iemcrp.com/

### Screenshots

- The module

org

- Suggested usage of components:

calendar

- Folder Structure

187472211-54602d24-d4c0-477f-b1b6-602e38182a77

### Additional information

- Only MUI and Styled components must be used
- Take reference from MUI Documentation about [Date pickers](https://mui.com/x/react-date-pickers/date-picker/) and [Date Range Pickers](https://mui.com/x/react-date-pickers/date-range-picker/)
- All folder structures must be maintained

## Happy contributing. 💐

Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by anuj98**
# Issue  📐

- **I anuj98 have worked for #32**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #32**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

image

image

  
  
  
---

### CODE REVIEW

**Comment by anuj98** [comment]
@warmachine028 Can you check the package lock file not sure why it updated a lot of things.

**Comment by warmachine028** [comment]
Don't worry. I will merge this PR and look into the `package-lock.json` myself

**Comment by warmachine028** [comment]
✅ Looks Good to me

**Review by warmachine028 — COMMENTED** [review]
LGTM✅

**Pull request merged**
