### PR TITLE
Feat/captcha

### LINKED ISSUE #72: CAPTCHA
### Description

- Currently only a static image is displayed in the place of captcha
- Find ways to generate real captcha and match it with user input.
- Discover React libraries to implement captcha Feature.
- The randomly generated captcha image being similar to the current static image is preferred style-wise
- However any new modifications in the generated image is allowed for consideration. 

### Screenshots

- Captcha Image

Screenshot_2022-10-04-11-05-03-91_40deb401b9ffe8e1df2f1cc5ba480b12

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by ozair-dev**
# Issue  📐

Added real captha instead of static captcha image. Please review the PR. This is the closest I can get to the static captcha image **style wise**

- **I Ozair have worked for #72**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #72**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  
Screenshot from 2022-10-22 23-42-38

  
  
---

### CODE REVIEW

**Comment by ozair-dev** [comment]
What is the meaning of this? What/why are you assigning me this?
Did you review the PR?

**Comment by warmachine028** [comment]
> What is the meaning of this? What/why are you assigning me this? Did you review the PR?

Your PR is under Review. I am assigning this as I assign all PRs to the people who made those, you can take a look at the previously merged PRs in this project.

**Comment by ozair-dev** [comment]
Aight mate, Sorry if I sounded rude. I was just confused.

**Comment by warmachine028** [comment]
> Aight mate, Sorry if I sounded rude. I was just confused.

Is alright @ozair-dev, you did a great job solving this issue ✨ which was long unsolved. Make sure to star 🌟 this repo. 
Will be merging this PR within a few minutes under `hacktoberfest-accepted`. 

Cheers,
Pritam

**Pull request merged**
