### PR TITLE
Making the grid items clickable only when hovering over the pictures 

### LINKED ISSUE #106: [FEATURE]  Making the grid items clickable only when hovering over the pictures
### Description

In the  dashboard, the object tiles below student details (the grid items) are clickable even in the whitespace (takes you to that tile's page. Could make it clickable only when hovering on pictures.

### Screenshots

_No response_

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by boltkk95**
# Issue  📐

- **I boltkk95 have worked for #106**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #106**

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

image
  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Why is this Icons not fully visible? Please Check it.

test

**Comment by boltkk95** [comment]
sorry about that,on it

**Comment by boltkk95** [comment]
@warmachine028 the issue was not able to get resolved completely as the mui library was very complicated when changing the styling. i have changed it  as it gets an overlay when hovering for now. please check it .

let me know your thoughts

**Review by warmachine028 — APPROVED** [review]

**Comment by warmachine028** [comment]
LGTM✅

**Pull request merged**
