### PR TITLE
Removed name field from paper component

### LINKED ISSUE #70: Remove Name Field
### Description

- The Icon already has a name below it.
- Name Component must not be present in the paper
- Remove the Name component

### Screenshots

Screenshot 2022-10-04 103530

### Additional information

- Please star this repo 🌟
- Make sure to read All contributing guidelines
- Also complete the Pull Request template stating your name and proper screenshots

### PR DESCRIPTION
**Pull request by GabrielWarner**
# Issue  📐

- **I Gabriel Warner have worked for Issue #70**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #70 **

## Screenshots 📷

**Here are the pictures of changes that i have made 🔽**

<attach screenshots here>
  BEFORE

image

  AFTER
image

  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
- The name must be visible below the icon.
- It must only be removed from the paper component.

Screenshot_2022-10-04-11-25-25-69_40deb401b9ffe8e1df2f1cc5ba480b12

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Name field must be visible below icon

**Comment by GabrielWarner** [comment]
Oh ok I will fix this

**Comment by warmachine028** [comment]
Correct!. Now make sure if this PR is being shown in your hacktoberfest profile, so that I can add `hacktoberfest-accepted` tag

**Comment by GabrielWarner** [comment]
Is this what you are talking about? This is literally my first contribution to open source :) This is the PR that it is linkinng to

image

**Review by warmachine028 — APPROVED** [review]

**Comment by warmachine028** [comment]
Great! Accepting 

> Is this what you are talking about? This is literally my first contribution to open source :) This is the PR that it is linkinng to
> 
> image

Yes it is being shown, now after I accept the PR it would `Waiting 7 Days`. 

Great Job ⭐ on your first contribution.

**Pull request merged**
